!!python/object/apply:collections.OrderedDict
- - - algo
    - ppo
  - - device
    - auto
  - - env
    - BipedalWalker-v3
  - - env_kwargs
    - null
  - - eval_episodes
    - 5
  - - eval_freq
    - 25000
  - - gym_packages
    - []
  - - hyperparams
    - clip_range: 0.18
      ent_coef: 0.0
      gamma: 0.999
      learning_rate: 0.0003
      n_envs: 32
  - - log_folder
    - logs/
  - - log_interval
    - -1
  - - max_total_trials
    - null
  - - n_eval_envs
    - 1
  - - n_evaluations
    - null
  - - n_jobs
    - 1
  - - n_startup_trials
    - 10
  - - n_timesteps
    - -1
  - - n_trials
    - 500
  - - no_optim_plots
    - false
  - - num_threads
    - -1
  - - optimization_log_path
    - null
  - - optimize_hyperparameters
    - false
  - - pruner
    - median
  - - sampler
    - tpe
  - - save_freq
    - -1
  - - save_replay_buffer
    - false
  - - seed
    - 901494559
  - - storage
    - null
  - - study_name
    - null
  - - tensorboard_log
    - runs/BipedalWalker-v3__ppo__901494559__1654177177
  - - track
    - true
  - - trained_agent
    - ''
  - - truncate_last_trajectory
    - true
  - - uuid
    - false
  - - vec_env
    - dummy
  - - verbose
    - 1
  - - wandb_entity
    - openrlbenchmark
  - - wandb_project_name
    - sb3
